import SignalAttachment from './attachment/SignalAttachment';
import { SignalAttachmentRegistration } from './attachment/SignalAttachment';
import GatewayAttachment from './attachment/GatewayAttachment';
import { GatewayAttachmentRegistration } from './attachment/GatewayAttachment';
import UdpAttachment from './attachment/UdpAttachment';
import { UdpAttachmentRegistration } from './attachment/UdpAttachment';
import HttpAttachment from './attachment/HttpAttachment';
import { HttpAttachmentRegistration } from './attachment/HttpAttachment';
import NoAnswerAttachment from './attachment/NoAnswerAttachment';
import { NoAnswerAttachmentRegistration } from './attachment/NoAnswerAttachment';
import Message from './common/Message';
import { MessageRegistration } from './common/Message';
import Error from './common/Error';
import { ErrorRegistration } from './common/Error';
import Heartbeat from './common/Heartbeat';
import { HeartbeatRegistration } from './common/Heartbeat';
import Ping from './common/Ping';
import { PingRegistration } from './common/Ping';
import Pong from './common/Pong';
import { PongRegistration } from './common/Pong';
import PairIntLong from './common/PairIntLong';
import { PairIntLongRegistration } from './common/PairIntLong';
import PairLong from './common/PairLong';
import { PairLongRegistration } from './common/PairLong';
import PairString from './common/PairString';
import { PairStringRegistration } from './common/PairString';
import PairLS from './common/PairLS';
import { PairLSRegistration } from './common/PairLS';
import TripleLong from './common/TripleLong';
import { TripleLongRegistration } from './common/TripleLong';
import TripleString from './common/TripleString';
import { TripleStringRegistration } from './common/TripleString';
import TripleLSS from './common/TripleLSS';
import { TripleLSSRegistration } from './common/TripleLSS';
import News from './news/News';
import { NewsRegistration } from './news/News';
import NewsStock from './news/NewsStock';
import { NewsStockRegistration } from './news/NewsStock';
import NewsConcept from './news/NewsConcept';
import { NewsConceptRegistration } from './news/NewsConcept';
import NewsRequest from './news/NewsRequest';
import { NewsRequestRegistration } from './news/NewsRequest';
import NewsResponse from './news/NewsResponse';
import { NewsResponseRegistration } from './news/NewsResponse';
import NewsOneRequest from './news/NewsOneRequest';
import { NewsOneRequestRegistration } from './news/NewsOneRequest';
import NewsOneResponse from './news/NewsOneResponse';
import { NewsOneResponseRegistration } from './news/NewsOneResponse';
import NewsLoadMoreRequest from './news/NewsLoadMoreRequest';
import { NewsLoadMoreRequestRegistration } from './news/NewsLoadMoreRequest';
import NewsLoadMoreResponse from './news/NewsLoadMoreResponse';
import { NewsLoadMoreResponseRegistration } from './news/NewsLoadMoreResponse';
import GaiNian from './gn/GaiNian';
import { GaiNianRegistration } from './gn/GaiNian';
import GnRequest from './gn/GnRequest';
import { GnRequestRegistration } from './gn/GnRequest';
import GnResponse from './gn/GnResponse';
import { GnResponseRegistration } from './gn/GnResponse';
import ChatgptMessageRequest from './chatgpt/ChatgptMessageRequest';
import { ChatgptMessageRequestRegistration } from './chatgpt/ChatgptMessageRequest';
import ChatgptMessageNotice from './chatgpt/ChatgptMessageNotice';
import { ChatgptMessageNoticeRegistration } from './chatgpt/ChatgptMessageNotice';
import ChatgptForceStopRequest from './chatgpt/ChatgptForceStopRequest';
import { ChatgptForceStopRequestRegistration } from './chatgpt/ChatgptForceStopRequest';
import ChatgptForceStopResponse from './chatgpt/ChatgptForceStopResponse';
import { ChatgptForceStopResponseRegistration } from './chatgpt/ChatgptForceStopResponse';
import ChatgptMessage from './chatgpt/ChatgptMessage';
import { ChatgptMessageRegistration } from './chatgpt/ChatgptMessage';
import ChatMessage from './chat/ChatMessage';
import { ChatMessageRegistration } from './chat/ChatMessage';
import GroupChatNotice from './chat/GroupChatNotice';
import { GroupChatNoticeRegistration } from './chat/GroupChatNotice';
import GroupChatRequest from './chat/GroupChatRequest';
import { GroupChatRequestRegistration } from './chat/GroupChatRequest';
import GroupHistoryMessageRequest from './chat/GroupHistoryMessageRequest';
import { GroupHistoryMessageRequestRegistration } from './chat/GroupHistoryMessageRequest';
import GroupHistoryMessageResponse from './chat/GroupHistoryMessageResponse';
import { GroupHistoryMessageResponseRegistration } from './chat/GroupHistoryMessageResponse';
import LoginRequest from './auth/LoginRequest';
import { LoginRequestRegistration } from './auth/LoginRequest';
import LoginResponse from './auth/LoginResponse';
import { LoginResponseRegistration } from './auth/LoginResponse';
import OssPolicyRequest from './auth/OssPolicyRequest';
import { OssPolicyRequestRegistration } from './auth/OssPolicyRequest';
import OssPolicyResponse from './auth/OssPolicyResponse';
import { OssPolicyResponseRegistration } from './auth/OssPolicyResponse';
import OssPolicyVO from './auth/OssPolicyVO';
import { OssPolicyVORegistration } from './auth/OssPolicyVO';
import LoginByWeChatRequest from './auth/LoginByWeChatRequest';
import { LoginByWeChatRequestRegistration } from './auth/LoginByWeChatRequest';
import LoginByWeChatResponse from './auth/LoginByWeChatResponse';
import { LoginByWeChatResponseRegistration } from './auth/LoginByWeChatResponse';
import User from './user/User';
import { UserRegistration } from './user/User';
import UserProfileNotice from './user/UserProfileNotice';
import { UserProfileNoticeRegistration } from './user/UserProfileNotice';
import UpdateUserProfileRequest from './user/UpdateUserProfileRequest';
import { UpdateUserProfileRequestRegistration } from './user/UpdateUserProfileRequest';
import UpdateUserProfileResponse from './user/UpdateUserProfileResponse';
import { UpdateUserProfileResponseRegistration } from './user/UpdateUserProfileResponse';
import GetUserProfileRequest from './user/GetUserProfileRequest';
import { GetUserProfileRequestRegistration } from './user/GetUserProfileRequest';
import GetUserProfileResponse from './user/GetUserProfileResponse';
import { GetUserProfileResponseRegistration } from './user/GetUserProfileResponse';
import MidImagineRequest from './midjourney/MidImagineRequest';
import { MidImagineRequestRegistration } from './midjourney/MidImagineRequest';
import MidHistoryRequest from './midjourney/MidHistoryRequest';
import { MidHistoryRequestRegistration } from './midjourney/MidHistoryRequest';
import MidImagineNotice from './midjourney/MidImagineNotice';
import { MidImagineNoticeRegistration } from './midjourney/MidImagineNotice';
import MidRerollRequest from './midjourney/MidRerollRequest';
import { MidRerollRequestRegistration } from './midjourney/MidRerollRequest';
import MidSelectRequest from './midjourney/MidSelectRequest';
import { MidSelectRequestRegistration } from './midjourney/MidSelectRequest';
import MidUpscaleRequest from './midjourney/MidUpscaleRequest';
import { MidUpscaleRequestRegistration } from './midjourney/MidUpscaleRequest';
import MidZoomRequest from './midjourney/MidZoomRequest';
import { MidZoomRequestRegistration } from './midjourney/MidZoomRequest';
import MidInpaintRequest from './midjourney/MidInpaintRequest';
import { MidInpaintRequestRegistration } from './midjourney/MidInpaintRequest';
import BrokerRegisterAsk from './broker/BrokerRegisterAsk';
import { BrokerRegisterAskRegistration } from './broker/BrokerRegisterAsk';
import BrokerRegisterAnswer from './broker/BrokerRegisterAnswer';
import { BrokerRegisterAnswerRegistration } from './broker/BrokerRegisterAnswer';
import MidImagineAsk from './broker/MidImagineAsk';
import { MidImagineAskRegistration } from './broker/MidImagineAsk';
import MidImagineNotify from './broker/MidImagineNotify';
import { MidImagineNotifyRegistration } from './broker/MidImagineNotify';
import MidRerollAsk from './broker/MidRerollAsk';
import { MidRerollAskRegistration } from './broker/MidRerollAsk';
import MidSelectAsk from './broker/MidSelectAsk';
import { MidSelectAskRegistration } from './broker/MidSelectAsk';
import MidUpscaleAsk from './broker/MidUpscaleAsk';
import { MidUpscaleAskRegistration } from './broker/MidUpscaleAsk';
import MidZoomAsk from './broker/MidZoomAsk';
import { MidZoomAskRegistration } from './broker/MidZoomAsk';
import MidInpaintAsk from './broker/MidInpaintAsk';
import { MidInpaintAskRegistration } from './broker/MidInpaintAsk';
import SeoAsk from './broker/SeoAsk';
import { SeoAskRegistration } from './broker/SeoAsk';
import SdSimulateAsk from './broker/SdSimulateAsk';
import { SdSimulateAskRegistration } from './broker/SdSimulateAsk';
import SdSimulateAnswer from './broker/SdSimulateAnswer';
import { SdSimulateAnswerRegistration } from './broker/SdSimulateAnswer';
import SdSimulateNotify from './broker/SdSimulateNotify';
import { SdSimulateNotifyRegistration } from './broker/SdSimulateNotify';
import StableDiffusionRequest from './sdiffusion/StableDiffusionRequest';
import { StableDiffusionRequestRegistration } from './sdiffusion/StableDiffusionRequest';
import StableDiffusionResponse from './sdiffusion/StableDiffusionResponse';
import { StableDiffusionResponseRegistration } from './sdiffusion/StableDiffusionResponse';
import StableDiffusionParameters from './sdiffusion/StableDiffusionParameters';
import { StableDiffusionParametersRegistration } from './sdiffusion/StableDiffusionParameters';
import InterrogatorPromptRequest from './sdiffusion/InterrogatorPromptRequest';
import { InterrogatorPromptRequestRegistration } from './sdiffusion/InterrogatorPromptRequest';
import InterrogatorPromptResponse from './sdiffusion/InterrogatorPromptResponse';
import { InterrogatorPromptResponseRegistration } from './sdiffusion/InterrogatorPromptResponse';
import SdSimulateRequest from './sdiffusion/SdSimulateRequest';
import { SdSimulateRequestRegistration } from './sdiffusion/SdSimulateRequest';
import SdSimulateNotice from './sdiffusion/SdSimulateNotice';
import { SdSimulateNoticeRegistration } from './sdiffusion/SdSimulateNotice';
import SdHistoryRequest from './sdiffusion/SdHistoryRequest';
import { SdHistoryRequestRegistration } from './sdiffusion/SdHistoryRequest';
import SdSimulateResponse from './sdiffusion/SdSimulateResponse';
import { SdSimulateResponseRegistration } from './sdiffusion/SdSimulateResponse';
import SdImage from './sdiffusion/SdImage';
import { SdImageRegistration } from './sdiffusion/SdImage';
import ImageDownloadRequest from './sdiffusion/ImageDownloadRequest';
import { ImageDownloadRequestRegistration } from './sdiffusion/ImageDownloadRequest';
import ImageDownloadResponse from './sdiffusion/ImageDownloadResponse';
import { ImageDownloadResponseRegistration } from './sdiffusion/ImageDownloadResponse';
import ImageDeleteAsk from './sdiffusion/ImageDeleteAsk';
import { ImageDeleteAskRegistration } from './sdiffusion/ImageDeleteAsk';
import TransferChatgptAsk from './chatgpt/TransferChatgptAsk';
import { TransferChatgptAskRegistration } from './chatgpt/TransferChatgptAsk';
import TransferChatgptNotify from './chatgpt/TransferChatgptNotify';
import { TransferChatgptNotifyRegistration } from './chatgpt/TransferChatgptNotify';
import AdminInfoRequest from './admin/AdminInfoRequest';
import { AdminInfoRequestRegistration } from './admin/AdminInfoRequest';
import AdminInfoResponse from './admin/AdminInfoResponse';
import { AdminInfoResponseRegistration } from './admin/AdminInfoResponse';
import Broadcast from './admin/Broadcast';
import { BroadcastRegistration } from './admin/Broadcast';
import DoBroadcastRequest from './admin/DoBroadcastRequest';
import { DoBroadcastRequestRegistration } from './admin/DoBroadcastRequest';
import DoBroadcastResponse from './admin/DoBroadcastResponse';
import { DoBroadcastResponseRegistration } from './admin/DoBroadcastResponse';
import DeleteBroadcastRequest from './admin/DeleteBroadcastRequest';
import { DeleteBroadcastRequestRegistration } from './admin/DeleteBroadcastRequest';
import DeleteBroadcastResponse from './admin/DeleteBroadcastResponse';
import { DeleteBroadcastResponseRegistration } from './admin/DeleteBroadcastResponse';
import SystemStatics from './admin/SystemStatics';
import { SystemStaticsRegistration } from './admin/SystemStatics';
import NewsStatics from './admin/NewsStatics';
import { NewsStaticsRegistration } from './admin/NewsStatics';
import IByteBuffer from "./IByteBuffer";
import IProtocolRegistration from "./IProtocolRegistration";

const protocols = new Map<number, IProtocolRegistration<unknown>>();
const protocolIdMap = new Map<any, number>();

// initProtocol
protocols.set(0, new SignalAttachmentRegistration());
protocolIdMap.set(SignalAttachment, 0);
protocols.set(2, new GatewayAttachmentRegistration());
protocolIdMap.set(GatewayAttachment, 2);
protocols.set(3, new UdpAttachmentRegistration());
protocolIdMap.set(UdpAttachment, 3);
protocols.set(4, new HttpAttachmentRegistration());
protocolIdMap.set(HttpAttachment, 4);
protocols.set(5, new NoAnswerAttachmentRegistration());
protocolIdMap.set(NoAnswerAttachment, 5);
protocols.set(100, new MessageRegistration());
protocolIdMap.set(Message, 100);
protocols.set(101, new ErrorRegistration());
protocolIdMap.set(Error, 101);
protocols.set(102, new HeartbeatRegistration());
protocolIdMap.set(Heartbeat, 102);
protocols.set(103, new PingRegistration());
protocolIdMap.set(Ping, 103);
protocols.set(104, new PongRegistration());
protocolIdMap.set(Pong, 104);
protocols.set(110, new PairIntLongRegistration());
protocolIdMap.set(PairIntLong, 110);
protocols.set(111, new PairLongRegistration());
protocolIdMap.set(PairLong, 111);
protocols.set(112, new PairStringRegistration());
protocolIdMap.set(PairString, 112);
protocols.set(113, new PairLSRegistration());
protocolIdMap.set(PairLS, 113);
protocols.set(114, new TripleLongRegistration());
protocolIdMap.set(TripleLong, 114);
protocols.set(115, new TripleStringRegistration());
protocolIdMap.set(TripleString, 115);
protocols.set(116, new TripleLSSRegistration());
protocolIdMap.set(TripleLSS, 116);
protocols.set(200, new NewsRegistration());
protocolIdMap.set(News, 200);
protocols.set(201, new NewsStockRegistration());
protocolIdMap.set(NewsStock, 201);
protocols.set(202, new NewsConceptRegistration());
protocolIdMap.set(NewsConcept, 202);
protocols.set(203, new NewsRequestRegistration());
protocolIdMap.set(NewsRequest, 203);
protocols.set(204, new NewsResponseRegistration());
protocolIdMap.set(NewsResponse, 204);
protocols.set(205, new NewsOneRequestRegistration());
protocolIdMap.set(NewsOneRequest, 205);
protocols.set(206, new NewsOneResponseRegistration());
protocolIdMap.set(NewsOneResponse, 206);
protocols.set(207, new NewsLoadMoreRequestRegistration());
protocolIdMap.set(NewsLoadMoreRequest, 207);
protocols.set(208, new NewsLoadMoreResponseRegistration());
protocolIdMap.set(NewsLoadMoreResponse, 208);
protocols.set(220, new GaiNianRegistration());
protocolIdMap.set(GaiNian, 220);
protocols.set(221, new GnRequestRegistration());
protocolIdMap.set(GnRequest, 221);
protocols.set(222, new GnResponseRegistration());
protocolIdMap.set(GnResponse, 222);
protocols.set(230, new ChatgptMessageRequestRegistration());
protocolIdMap.set(ChatgptMessageRequest, 230);
protocols.set(231, new ChatgptMessageNoticeRegistration());
protocolIdMap.set(ChatgptMessageNotice, 231);
protocols.set(232, new ChatgptForceStopRequestRegistration());
protocolIdMap.set(ChatgptForceStopRequest, 232);
protocols.set(233, new ChatgptForceStopResponseRegistration());
protocolIdMap.set(ChatgptForceStopResponse, 233);
protocols.set(234, new ChatgptMessageRegistration());
protocolIdMap.set(ChatgptMessage, 234);
protocols.set(240, new ChatMessageRegistration());
protocolIdMap.set(ChatMessage, 240);
protocols.set(241, new GroupChatNoticeRegistration());
protocolIdMap.set(GroupChatNotice, 241);
protocols.set(242, new GroupChatRequestRegistration());
protocolIdMap.set(GroupChatRequest, 242);
protocols.set(243, new GroupHistoryMessageRequestRegistration());
protocolIdMap.set(GroupHistoryMessageRequest, 243);
protocols.set(244, new GroupHistoryMessageResponseRegistration());
protocolIdMap.set(GroupHistoryMessageResponse, 244);
protocols.set(250, new LoginRequestRegistration());
protocolIdMap.set(LoginRequest, 250);
protocols.set(251, new LoginResponseRegistration());
protocolIdMap.set(LoginResponse, 251);
protocols.set(252, new OssPolicyRequestRegistration());
protocolIdMap.set(OssPolicyRequest, 252);
protocols.set(253, new OssPolicyResponseRegistration());
protocolIdMap.set(OssPolicyResponse, 253);
protocols.set(254, new OssPolicyVORegistration());
protocolIdMap.set(OssPolicyVO, 254);
protocols.set(255, new LoginByWeChatRequestRegistration());
protocolIdMap.set(LoginByWeChatRequest, 255);
protocols.set(256, new LoginByWeChatResponseRegistration());
protocolIdMap.set(LoginByWeChatResponse, 256);
protocols.set(260, new UserRegistration());
protocolIdMap.set(User, 260);
protocols.set(261, new UserProfileNoticeRegistration());
protocolIdMap.set(UserProfileNotice, 261);
protocols.set(262, new UpdateUserProfileRequestRegistration());
protocolIdMap.set(UpdateUserProfileRequest, 262);
protocols.set(263, new UpdateUserProfileResponseRegistration());
protocolIdMap.set(UpdateUserProfileResponse, 263);
protocols.set(264, new GetUserProfileRequestRegistration());
protocolIdMap.set(GetUserProfileRequest, 264);
protocols.set(265, new GetUserProfileResponseRegistration());
protocolIdMap.set(GetUserProfileResponse, 265);
protocols.set(270, new MidImagineRequestRegistration());
protocolIdMap.set(MidImagineRequest, 270);
protocols.set(271, new MidHistoryRequestRegistration());
protocolIdMap.set(MidHistoryRequest, 271);
protocols.set(272, new MidImagineNoticeRegistration());
protocolIdMap.set(MidImagineNotice, 272);
protocols.set(273, new MidRerollRequestRegistration());
protocolIdMap.set(MidRerollRequest, 273);
protocols.set(274, new MidSelectRequestRegistration());
protocolIdMap.set(MidSelectRequest, 274);
protocols.set(275, new MidUpscaleRequestRegistration());
protocolIdMap.set(MidUpscaleRequest, 275);
protocols.set(276, new MidZoomRequestRegistration());
protocolIdMap.set(MidZoomRequest, 276);
protocols.set(277, new MidInpaintRequestRegistration());
protocolIdMap.set(MidInpaintRequest, 277);
protocols.set(300, new BrokerRegisterAskRegistration());
protocolIdMap.set(BrokerRegisterAsk, 300);
protocols.set(301, new BrokerRegisterAnswerRegistration());
protocolIdMap.set(BrokerRegisterAnswer, 301);
protocols.set(302, new MidImagineAskRegistration());
protocolIdMap.set(MidImagineAsk, 302);
protocols.set(303, new MidImagineNotifyRegistration());
protocolIdMap.set(MidImagineNotify, 303);
protocols.set(304, new MidRerollAskRegistration());
protocolIdMap.set(MidRerollAsk, 304);
protocols.set(305, new MidSelectAskRegistration());
protocolIdMap.set(MidSelectAsk, 305);
protocols.set(306, new MidUpscaleAskRegistration());
protocolIdMap.set(MidUpscaleAsk, 306);
protocols.set(307, new MidZoomAskRegistration());
protocolIdMap.set(MidZoomAsk, 307);
protocols.set(308, new MidInpaintAskRegistration());
protocolIdMap.set(MidInpaintAsk, 308);
protocols.set(320, new SeoAskRegistration());
protocolIdMap.set(SeoAsk, 320);
protocols.set(321, new SdSimulateAskRegistration());
protocolIdMap.set(SdSimulateAsk, 321);
protocols.set(322, new SdSimulateAnswerRegistration());
protocolIdMap.set(SdSimulateAnswer, 322);
protocols.set(323, new SdSimulateNotifyRegistration());
protocolIdMap.set(SdSimulateNotify, 323);
protocols.set(330, new StableDiffusionRequestRegistration());
protocolIdMap.set(StableDiffusionRequest, 330);
protocols.set(331, new StableDiffusionResponseRegistration());
protocolIdMap.set(StableDiffusionResponse, 331);
protocols.set(332, new StableDiffusionParametersRegistration());
protocolIdMap.set(StableDiffusionParameters, 332);
protocols.set(333, new InterrogatorPromptRequestRegistration());
protocolIdMap.set(InterrogatorPromptRequest, 333);
protocols.set(334, new InterrogatorPromptResponseRegistration());
protocolIdMap.set(InterrogatorPromptResponse, 334);
protocols.set(340, new SdSimulateRequestRegistration());
protocolIdMap.set(SdSimulateRequest, 340);
protocols.set(341, new SdSimulateNoticeRegistration());
protocolIdMap.set(SdSimulateNotice, 341);
protocols.set(342, new SdHistoryRequestRegistration());
protocolIdMap.set(SdHistoryRequest, 342);
protocols.set(343, new SdSimulateResponseRegistration());
protocolIdMap.set(SdSimulateResponse, 343);
protocols.set(344, new SdImageRegistration());
protocolIdMap.set(SdImage, 344);
protocols.set(345, new ImageDownloadRequestRegistration());
protocolIdMap.set(ImageDownloadRequest, 345);
protocols.set(346, new ImageDownloadResponseRegistration());
protocolIdMap.set(ImageDownloadResponse, 346);
protocols.set(347, new ImageDeleteAskRegistration());
protocolIdMap.set(ImageDeleteAsk, 347);
protocols.set(402, new TransferChatgptAskRegistration());
protocolIdMap.set(TransferChatgptAsk, 402);
protocols.set(403, new TransferChatgptNotifyRegistration());
protocolIdMap.set(TransferChatgptNotify, 403);
protocols.set(10000, new AdminInfoRequestRegistration());
protocolIdMap.set(AdminInfoRequest, 10000);
protocols.set(10001, new AdminInfoResponseRegistration());
protocolIdMap.set(AdminInfoResponse, 10001);
protocols.set(10002, new BroadcastRegistration());
protocolIdMap.set(Broadcast, 10002);
protocols.set(10003, new DoBroadcastRequestRegistration());
protocolIdMap.set(DoBroadcastRequest, 10003);
protocols.set(10004, new DoBroadcastResponseRegistration());
protocolIdMap.set(DoBroadcastResponse, 10004);
protocols.set(10010, new DeleteBroadcastRequestRegistration());
protocolIdMap.set(DeleteBroadcastRequest, 10010);
protocols.set(10011, new DeleteBroadcastResponseRegistration());
protocolIdMap.set(DeleteBroadcastResponse, 10011);
protocols.set(10050, new SystemStaticsRegistration());
protocolIdMap.set(SystemStatics, 10050);
protocols.set(10051, new NewsStaticsRegistration());
protocolIdMap.set(NewsStatics, 10051);

class ProtocolManager {
    static getProtocolId(clazz: any): number {
        const protocolId = protocolIdMap.get(clazz);
        if (protocolId === null || protocolId === undefined) {
            throw '[protocol:' + clazz + '] not exist';
        }
        return protocolId;
    }

    static getProtocol(protocolId: number): IProtocolRegistration<unknown> {
        const protocol = protocols.get(protocolId);
        if (protocol === null || protocol === undefined) {
            throw '[protocolId:' + protocolId + '] not exist';
        }
        return protocol;
    }

    static write(buffer: IByteBuffer, packet: any): void {
        const protocolId = ProtocolManager.getProtocolId(packet.constructor);
        buffer.writeShort(protocolId);
        const protocol = ProtocolManager.getProtocol(protocolId);
        protocol.write(buffer, packet);
    }

    static read(buffer: IByteBuffer): any {
        const protocolId = buffer.readShort();
        const protocol = ProtocolManager.getProtocol(protocolId);
        const packet = protocol.read(buffer);
        return packet;
    }
}

export default ProtocolManager;